### PR TITLE
show reason as tooltip in participations projects

### LINKED ISSUE #432: Projects: add reason
feedback from ms2

- [x] backend: add reason attibute to participation
- [x] frontend: add textfield for reason participation

### LINKED ISSUE #497: projects:participations: show reason

### PR DESCRIPTION
**Pull request by QuintenVervynck**
added the option to add a reason to a participation
Fixes #432

we needed a way to show the reason of a participation in projects 
I made it a tooltip, because I didn't want to directly show that string of information for every participation
Fixes #497

### CODE REVIEW

**Comment by QuintenVervynck** [comment]
this is what it looks like (the reason is "hello" now)
image

And not this doesn't mess with the tooltip for the deletion of a participation
image

**Comment by StefVdHaute** [comment]
Is it possible to also add the user that assigned the student to that project? I remembered an issue about that but i can't find it right now.

**Review by victormylle — APPROVED** [review]

**Comment by QuintenVervynck** [comment]
@StefVdHaute I found it in the nice to have section https://github.com/SELab-2/OSOC-4/issues/233

**Comment by StefVdHaute** [comment]
I'll continue the conversation there then.

**Pull request merged**
