### PR TITLE
slight studentlistelement improvement for smaller screens

### PR DESCRIPTION
**Pull request by StefVdHaute**
StudentListelements became quite big with lot's of open space when they were small. This pull request improves this slightly but it's not super great.

Before:
image
After:
image

### CODE REVIEW

**Review by SimonVandeVyver — CHANGES_REQUESTED** [review]
The skills are not aligned on the right anymore:
image
Besides that, the studentListement looks good on small screens.

**Comment by StefVdHaute** [comment]
Is that full screen? If yes i made a mistake, if no that's the way it was before these changes and i was not able to find a fix.

**Comment by SimonVandeVyver** [comment]
Yes, on full screen I had this problem.

**Review by SimonVandeVyver — APPROVED** [review]
The responsiveness when making it smaller is still not perfect, but it is better then before.

**Pull request merged**
