### PR TITLE
projects improved responsiveness

### PR DESCRIPTION
**Pull request by thabils**
closes #597

### CODE REVIEW

**Comment by StefVdHaute** [comment]
Probably the most detailed responsiveness i've ever done. I beg you to start from full screen and to go gradually smaller from that point to see what i did.

**Comment by QuintenVervynck** [comment]
this is really bad.

this is my screen in full width

Screenshot 2022-05-22 at 09 39 40

and this is like 98% of my screen width

Screenshot 2022-05-22 at 09 40 11

while i used to be able to almost put 2 full projects pages on my screen side by side.

This will for sure be a problem on the demo where the beamer probably won't have a lot of pixels.

**Review by QuintenVervynck — CHANGES_REQUESTED** [review]
see my previous comment, this can't be merged.

It switches to "a smaller screen" way too fast.

**Comment by StefVdHaute** [comment]
I don't remember that being the case before the merge. Will check out after i've eaten.

**Comment by StefVdHaute** [comment]
> Probably the most detailed responsiveness i've ever done. I beg you to start from full screen and to go gradually smaller from that point to see what i did.

This was also referring to what it looks like in smaller widths when projects are shown. Not 95+% width. I was not aware of this issue

**Review by QuintenVervynck — APPROVED** [review]
looks way better, thanks!

**Pull request merged**
