### PR TITLE
Frontend delete participation

### PR DESCRIPTION
**Pull request by thabils**
Frontend to delete participation

### CODE REVIEW

**Comment by thabils** [comment]
fixes #350 but gives other problems

**Comment by Vital7788** [comment]
Creating new participations after deleting works for me in the backend. Maybe the problem is in the frontend?

**Comment by thabils** [comment]
> Creating new participations after deleting works for me in the backend. Maybe the problem is in the frontend?

Yes it was it should be fixed now.

**Review by SimonVandeVyver — CHANGES_REQUESTED** [review]
I can not remove participations from the details of a project, I think this does not work yet.

**Pull request closed without merging**
